# Generated by Django 6.1.1 on 2026-09-03 05:31

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_numbers', models.JSONField(blank=True, default=list)),
                ('emails', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('location_locality', models.CharField(blank=True, max_length=100, null=True)),
                ('location_region', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('job_company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('linkedin_username', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_connections', models.FloatField(default=0)),
                ('inferred_years_experience', models.FloatField(default=0)),
                ('inferred_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('profiles', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('search_text', models.TextField(blank=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['full_name'], name='home_linked_full_na_913855_idx'), models.Index(fields=['location'], name='home_linked_locatio_19792a_idx'), models.Index(fields=['job_title'], name='home_linked_job_tit_3d3950_idx'), django.contrib.postgres.indexes.GinIndex(fields=['skills'], name='home_linked_skills_5c6751_gin'), django.contrib.postgres.indexes.GinIndex(fields=['experience'], name='home_linked_experie_3d5fba_gin'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='home_linked_search__7b714f_gin')],
            },
        ),
    ]
