# Generated by Django 6.1.1 on 2026-09-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='linkedinprofile',
            name='home_linked_skills_5c6751_gin',
        ),
        migrations.RemoveIndex(
            model_name='linkedinprofile',
            name='home_linked_experie_3d5fba_gin',
        ),
        migrations.RemoveIndex(
            model_name='linkedinprofile',
            name='home_linked_search__7b714f_gin',
        ),
        migrations.RemoveField(
            model_name='linkedinprofile',
            name='search_vector',
        ),
    ]
